### ISSUE TITLE
IE11 compatibility in 1.0.11 version

### ISSUE THREAD

**Issue by KalachevDev** [kaelzhang/b2a#4]
Hey! We upgraded b2a dependency recently and faced following issue:

You specified **module: src/index.js** in package.json file and as a result webpack treat it as a module root, but it's not IE11 compatible. I've created a workaround, but can we do something to make it IE11 compatible back? :) I could raise a PR if it is needed. Thanks in advice!

**Comment by kaelzhang** [comment]
I think we can use `babel-loader` for webpack.

```js
module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  }
```

**Comment by KalachevDev** [comment]
@kaelzhang do you mean add this to our codebase? That's actually one of workarounds I was thinking about. But for me it seems a bit odd to transpile dependencies.

**Comment by kaelzhang** [comment]
IMO the only problem is that `babel-loader` might slow down the compile phase of your project.

If `b2a` or every other javascript library compiles the module entry to target ie 11, and if somebody has a project which should be compatible with ie8, he still needs the `babel-loader`. 

Then maybe another guy creates a project that only works for chrome, the polyfills(and ponyfills) of `b2a` for ie11 are completely unnecessary for him and also bad for performance.  

So, I'd like not to compile the module entry of any library unless it contains some syntaxes which are not of ECMA standards.

**Comment by KalachevDev** [comment]
@kaelzhang gotcha. Thanks for answering, will stick with adding babel configuration!

**Comment by kaelzhang** [comment]
Thanks for your understanding 😄

**Comment by KalachevDev** [comment]
By the way, I was always thinking that **main** property in package.json is treated as module root. But that's not the truth (and also there is file lib/index.js that contains transpiled and IE compatible code, what's the purpose of it then?)

**Comment by kaelzhang** [comment]
The `main` field of package.json indicates the entry for nodejs. And for most scenarios, we should not rely on babel(babel-node for example) to run a node application.
